export const SET_SEARCH_TERM = "[SEARCH TERM] SET SEARCH TERM FILTER BY SEARCH ACTION";
export const SET_FILTER_VALUE= "[FILTER VALUE] SET FILTER VALUE TO FILTER ALL COLORS FROM THE LIST";

export const SET_FILTERS_VALUES = "[SET FILTERS VALUES] SET FILTER VALUES TO FILTER ALL COLORS FROM THE LIST";


